### ISSUE TITLE
Test suite doesn't build on darwin

### ISSUE THREAD

**Issue by sternenseemann** [typeclasses/dsv#1]
Due to the case insensitive nature of darwin's file system GHC will complain that it can't distinguish between `hedgehog.hs` which is supposedly a `Main` module and the `Hedgehog` module in scope, resulting in the following, quite confusing error:

```
test/Hedgehog.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘Hedgehog’
```

Renaming the test entrypoint to `Main.hs` or similar should fix this.

**Comment by chris-martin** [comment]
Exciting! Reproduced in CI here: https://github.com/typeclasses/dsv/runs/3278115240?check_suite_focus=true Will release a fix.

**Comment by chris-martin** [comment]
Released https://hackage.haskell.org/package/dsv-1.0.0.2
